use std::collections::BTreeMap;

use aide::axum::ApiRouter;
use kinded::{Kind, Kinded};

use crate::*;

/// Domain entry point — carries domain identity and the dispatch methods.
/// The dispatch (meta_for, handler_for) is generated by the `resource_root!`
/// macro from a simple variant list. Each leaf's data comes from its
/// `Annotated<ResourceMeta>` and `Annotated<ResourceHandler>` impls.
///
/// Not all kind variants need annotations — some are CLI-only operations
/// (e.g. export, import, replay) that don't have HTTP routes or skills.
/// `meta_for` and `handler_for` return `None` for those, and `router()` /
/// `skills()` skip them.
pub(crate) trait ResourceRoot: Kinded
where
    <Self as Kinded>::Kind: Kind + core::fmt::Display,
{
    const LABEL: &'static str;
    const PURPOSE: &'static str;

    /// Route prefix for this domain. Defaults to LABEL.
    const PREFIX: &'static str = Self::LABEL;

    fn meta_for(kind: <Self as Kinded>::Kind) -> Option<ResourceMeta>;
    fn handler_for(kind: <Self as Kinded>::Kind) -> Option<ResourceHandler>;

    fn tag() -> Tag {
        Tag::builder()
            .name(Self::LABEL)
            .description(Self::PURPOSE)
            .build()
    }

    fn resource_docs(kind: <Self as Kinded>::Kind) -> ResourceDocs {
        let meta = Self::meta_for(kind).expect("annotated kind should have meta");
        ResourceDocs::builder()
            .tag(Self::tag())
            .nickname(kind.to_string())
            .summary(meta.summary)
            .description(meta.description)
            .build()
    }

    fn router() -> ApiRouter<ServerState>
    where
        Self: Sized,
        <Self as Kinded>::Kind: 'static,
    {
        let mut by_path: BTreeMap<&'static str, Vec<<Self as Kinded>::Kind>> = BTreeMap::new();
        for kind in <Self as Kinded>::Kind::all() {
            if let Some(meta) = Self::meta_for(*kind).filter(|_| Self::handler_for(*kind).is_some())
            {
                by_path.entry(meta.path).or_default().push(*kind);
            }
        }

        let mut inner = ApiRouter::<ServerState>::new();
        for (path, kinds) in by_path {
            let methods = kinds
                .into_iter()
                .map(|kind| {
                    let handler =
                        Self::handler_for(kind).expect("kind in router should have handler");
                    let docs = Self::resource_docs(kind);
                    (handler.build)(&docs)
                })
                .reduce(|a, b| a.merge(b))
                .unwrap();
            inner = inner.api_route(path, methods);
        }

        ApiRouter::new().nest(&format!("/{}", Self::PREFIX), inner)
    }

    fn skills() -> Vec<Skill>
    where
        Self: Sized,
        <Self as Kinded>::Kind: 'static,
    {
        <Self as Kinded>::Kind::all()
            .iter()
            .filter_map(|kind| {
                Self::meta_for(*kind).map(|meta| {
                    Skill::builder()
                        .name(kind.to_string())
                        .content(meta.content)
                        .build()
                })
            })
            .collect()
    }
}
